name: '${project.name}'
version: '${project.version}'
# TODO: Change the main, loader and bootstrapper classes accordingly when you refactor.
main: cc.daniel.danielplugintemplate.DanielPluginTemplate
loader: cc.daniel.danielplugintemplate.load.DanielLibraryLoader
bootstrapper: cc.daniel.danielplugintemplate.load.DanielPluginBootstrap
api-version: '1.21'
authors:
  - Author name here
